### ISSUE TITLE
astcenc_compress_image does not play well with task graphs

### ISSUE THREAD

**Issue by Themaister** [ARM-software/astc-encoder#130]
I'm trying to integrate the new astcenc API into Granite, and astcenc_compress_image relies on all threads to be run fully concurrent to be able to compress an image as a compute-style barrier() is used inside the implementation. However, this is problematic in a task graph where we cannot (and should not) guarantee that all threads are run concurrently. It also limits how finely granulated we can make the parallelism.

**Comment by solidpixel** [comment]
Yes, this is on the "to improve" list. FWIW this was true in the 1.x series too (in as far as the assignment of blocks to each thread was static unless you hooked in directly to the lowest level block compress function, so a sparse thread invocation with the higher level functions would result in an image containing missing blocks). 

The main concern in the current design was avoiding racy behavior if you have threads arriving somewhat intermittently as they complete other work, because the current API doesn't have an "compress_init" to reset the thread state tracker before each compression pass. By forcing convergence the barrier design can:

* Guarantee all threads are inside compress() and so see the right version of the thread state.
* Guarantee all threads have left compress only when the state is reset for another compression.

If we want an arbitrary thread count where less than the N allocated thread slots are used, and where threads may enter compress() at any time, then we need some other means to synchronise the state. Options:

**Option one:** Allow any value of actual threads (<= N), but caller must guarantee that there is at least a thread zero (which we can give special powers to "clock-in / clock-out").

**Option two:** Add another function to the API to initialize a new compression pass. Allow any value of actual threads (<=N), with no requirement of which thread IDs are used - we use the new compress_init to clock-in/clock-out the state tracker.

Thoughts?

**Comment by Themaister** [comment]
My current hack will be exposing the different compression stages in separate chunks so the caller can schedule work as it sees fit, and caller needs to ensure synchronization between stages.

**Comment by solidpixel** [comment]
This seems relatively straight forward to fix if we accept the compress_init or reset function - hopeful to get this in for 2.0.

**Comment by solidpixel** [comment]
Prototype of the new parallel task manager. Allows for a single-threaded init stage (packaged as a lambda) serviced by the first thread to arrive at that point in the pipeline, and a dynamic dispatch of tasks to worker threads for the main parallel processing stage after that point.

* https://github.com/ARM-software/astc-encoder/blob/rethread/thread_demo.cpp

Not plumbed into the codec yet, so the codec on this branch is currently non-functional as I've pulled out the Barrier implementation in preparation for plumbing this in.

**Comment by solidpixel** [comment]
@Themaister Here's an initial implementation if you can spare a review to check it does what you want:

* https://github.com/ARM-software/astc-encoder/pull/134

Limitations:
* You still need to declare the max allowed thread count `N` when creating the context (that allocates the scratch resources the threads use).
* Each thread that enters the function must use a unique thread ID in the range `[0 .. N-1]` (this will be the array index of the scratch buffers). 

Any subset of the threads in that range entering `compress()` is valid and can complete a compression, and in addition thread 0 is no longer special - the first thread to arrive can do initialization.

Added bonus - it's about 1-2% faster than the prior implementation =)

**Comment by solidpixel** [comment]
PR has been merged so we can soak test it- let me know if you have any feedback.
