### ISSUE TITLE
The config flags are a bit confusing.

### ISSUE THREAD

**Issue by Themaister** [ARM-software/astc-encoder#131]
The astc config takes some flags to initialize the astc_config struct. It is somewhat unclear to me how to configure the encoder for optimal results for different use cases. I think the API could be improved if there were specific modes tuned towards the common use cases.

## RGBA

This is fine as-is.

## RGB (color, emissive)

For non-alpha textures, I couldn't find a good way to tell the encoder "don't care about alpha".
It feels a bit icky to set `cw_a_weight = 0.0` after initializing the config. I don't remember off the top of my head if there is an endpoint encoding format which just has 3 components, otherwise I guess the best we can do is just swizzle in 1 for A anyways.

There is an alpha weight flag, but that seems only relevant when using alpha in a certain way, not to specify "I'm not using alpha".

## Normal map

I've pre-swizzled the image to RRRW to be able to take advantage of L+A format. There is also a flag to use MAP_NORMAL, so this seems fine.

## PBR (Metallic-roughness)

In BC5, this is very easy since the two channels are completely decorrelated, but I can't find a good way to express this decorrelation in astcenc. I pre-swizzle to RRRW to get two component blocks, but I cannot find a good way to hint about decorrelation. I'm seeing some artifacting I do not expect with PBR maps (BC5 looks way better at similar BPP), which I believe is caused by something I'm not doing right with the API.

**Comment by solidpixel** [comment]
Thanks for the feedback.

### RGB (color, emissive)

ASTC is always conceptually four components in the color-endpoint. If you want no-alpha in terms of bit cost you must swizzle on encode to the `RGB1` form to hit the constant a=1 CEM encoding. Using things like channel weights with a non-1 alpha will still encode an alpha channel value, just in a very relaxed fashion with high error. Adding a new RGB mode flag, along with an API to get the recommended encoding swizzle (which a power user could choose to ignore) seems like a good idea. Will aim to do this for 2.0 for both the API and the command line it's a common usage model.

The alpha weighting flag is indeed a different beast (about ensuring alpha keeps quality in areas where RGB doesn't need the bits because it's almost transparent). 

### PBR (Metallic-roughness)

The MASK_MAP mode can help for cases with decorrelated channels - it aims to avoid error bleed across channels as much as possible. Happy to look at more detail if you can share a repro - you have my email if you can't share here.

**Comment by solidpixel** [comment]
P.S. If you've not seen it the recommended swizzles for encode and sampling are here:

https://github.com/ARM-software/astc-encoder/blob/master/Docs/Encoding.md#astc-format-mapping

**Comment by Themaister** [comment]
That readme is helpful, thanks.

**Comment by solidpixel** [comment]
After some thought I'm leaning away from an API change for the RGB mode; I think we just need to improve the API documentation in the header to explain common usage.

**Comment by solidpixel** [comment]
Improved header documentation for channel count mapping to swizzle recommendations added in commit 1a2a73a. Closing this; let me know if you think we need to do more here.
