### ISSUE TITLE
srgb-alpha png get a bad compress result 

### ISSUE THREAD

**Issue by w1t1** [ARM-software/astc-encoder#192]
i have a srgb with alpha picture,i used -cs 6x6 param to compress this picture,but i got a bad astc file,i upload the picture,could you help me to solve this problem,Thank you.
source pic: 
![1_srgb](https://user-images.githubusercontent.com/45480740/103344658-2cc6b000-4aca-11eb-830a-0929fff5131d.png)

result picture: 
![result](https://user-images.githubusercontent.com/45480740/103344695-4536ca80-4aca-11eb-9ad9-6b11314ebf15.png)

**Comment by solidpixel** [comment]
I can see two issues here:

Firstly, it looks like you are compressing to sRGB but sampling using it as a linear format in the API. This is why it looks a lot darker than you expect; the sRGB gamma conversion isn't getting applied. The sRGB ASTC formats have their own format enums in the API which you'll need to use. 

Secondly, it looks like you've not flipped the Y coordinates. For historical reasons `astcenc` uses DX coordinates: (0,0) is top left, not bottom left like the Khronos APIs. Use `-yflip` when compressing to correct the coordinates for the Khronos APIs.

HTH,
Pete

**Comment by solidpixel** [comment]
Thinking about it, I reversed my logic - sampling sRGB data directly as a linear value without color space conversion should appear lighter not darker. Can you share a more complete reproducer, including how you are visualizing the image?

Does the same issue occur with linear format images? To be clear here, I'm pretty sure that the problem is outside of astcenc. Nothing in the compressor actually applies any form of color space conversion; the sRGB data is directly encoded just like linear data. The only CSC happens during sampling on the GPU hardware.

**Comment by w1t1** [comment]
Thanks for your suggestion,I visualizing the compress picture in qt5.15 and opengl texture. The problem is that images require  pre-multiplication alpha before compress. After do it, i get the correct display in qt and opengl.Thanks for you help!
