### ISSUE TITLE
Request for linear endpoint encode with setting to do final convert to srgb on endpoints.

### ISSUE THREAD

**Issue by alecazam** [ARM-software/astc-encoder#244]
All of the block encoders currently take in one set of colors.  Typically these are 8-bit sRGB colors.  But that's a non-linear space to fit a line through for gradients.   

I want to be able to pass linear colors for the block, and after color fitting, have the encoder convert them to srgb before they are split into base + offset or just the 8-bit channels.   Pitch for a proposal for the encode/decode to allow srgb as a flag on each block.  That way the higher-bit depth endpoints can converted instead of attempting this after snapping to 8-bit.  This also then ties in with how the sampler undoes sRGB.

ASTC has 8-bit endpoints unlike BC1/3.  I tried doing this with BC1/3, but with 565 there really isn't enough data to then convert the endpoints to srgb after.

This requires no hardware changes, but could result in better reconstruction of srgb images like albedo or photo imagery.

**Comment by solidpixel** [comment]
Hi Alec, 

I'm not sure I understand the issue you're trying to solve here.

Three points of note:

Firstly, sRGB is a perceptually linear distribution, so it's typically far better behaved for things like color gradients than linear RGB, because any perceptual error introduced is evenly distributed across the gradient line segment. What are you gaining by passing in linear data over just passing in sRGB data?

Secondly, late conversion from linear to sRGB just for endpoint encoding doesn't really work unless you are passing in 16-bit per component linear data to start off with. If your input content is authored in 8-bit linear then you have already lost the information needed to do a decent sRGB encode (dark colors have already been quantized). If you do have 16-bit linear LDR input data, just implement the 16 linear to 8-bit sRGB conversion as a preprocess before calling the compressor (given that the sRGB decompress is explicitly 8-bit UNORM per component it can't preserve more than that).

Finally, the use of sRGB isn't a per-block choice. It's part of the texture format enum - it's either on or off for the whole image.

**Comment by alecazam** [comment]
> Finally, the use of sRGB isn't a per-block choice. It's part of the texture format enum - it's either on or off for the whole image.

Yes, this flag would be set across all blocks and all mips.  It's just saying "I'm sending in linear data", but fit and fixup the endpoints to sRGB as late as possible.

When my encoder runs with srgb and premul data, I already have to go to linear space for mip generation.  That means at least 16f color data with 10-bits of precision.  I don't think it makes sense to build the mips in srgb space without that conversion, so I'm wondering why it's okay to fit a point cloud to the sRGB colors.  I can see the error metrics delta-ing off the linear or the sRGB pixel colors as you said.  I would have done this myself, but ASTC doesn't always store the endpoints in one spot like BC, so I was hoping the block encoder might accept a flag on this.

Correct me if I'm wrong here, but does the hardware texture unit decode do 

1)   lerp(srgbToLinear(e0), srgbToLinear(e1), selector)

or 

2) srgbToLinear(lerp(e0, e1, selector))

I'm assuming 1, but the way if you're fitting sRGB colors then the hw decode needs to be 2.  So then the lerp is on the linear data (and possibly premul data).  Hopefully also that lookup for srgbToLinear is a little higher bit depth than 8 when stored in the texture cache.  Then bi/tri/aniso lookup are all nicely in linear space.  I hope the idea doesn't sound crazy.

**Comment by solidpixel** [comment]
> ... does the hardware texture unit decode do (1) or (2)

For ASTC the decompressor is specified to lerp between endpoints entirely in sRGB color space, so (2). 

The main reason for this is that it is highly desirable to keep the 8-bit decompressed sRGB in the texture cache; if you linearize before storing in the cache you need need 16-bit decompressed intermediates to preserve the accuracy of the gamma curve, which effectively halves your cache capacity. ASTC sRGB decompression is explicitly specified as returning 8-bit sRGB encoded texels. sRGB conversion happens "later"; e.g. during sampling.

> I'm wondering why it's okay to fit a point cloud to the sRGB colors.

There is nothing wrong with filtering in a non-linear gamma as long as you have an appropriate non-linear aware interpolation factor. 

Mipmapping and other such areas cannot use gamma space filtering because when mixing endpoints you expect the mixing factor to behave as if the inputs were linear. E.g. for a 2x2 box filter downsample for a mipmap using a 0.25 weight per input sample is only true if the inputs are linear.

For ASTC during compression we don't expect the mixing factor for sRGB textures to behave as if the inputs were linear, we are free to choose a weight knowing that we're going to lerp in sRGB domain. This definitely isn't the same weight you'd need to use for a linear-space lerp to get the same output color.

**Comment by alecazam** [comment]
Thanks Pete.  I had assumed the conversion was higher bit depth, but I can see where one stage does decode to srgb, and the next srgb -> linear color lookup off those values.  So ASTC block produces all srgb block pixels when enabled.  Might be worth a presentation on that.

Here's my problem with the math.  When you're storing premul data what you really have is:
rgb_e0 = srgbFromLinear(rgb_linear * a)  

So the reverse of that
srgbToLinear(rgb_e0) -> lerp(rgb_linear_e0*a, rgb_linear_e1*a, selector) 

So ideally, you'd convert to linear, and lerp the linear premul color.  Otherwise, don't you have a non-linear interpretation of rgb*a?  That seems like the price of keeping things 8-bit.

**Comment by solidpixel** [comment]
For premul, I think the same argument applies as for sRGB - it doesn't matter. 

Compression is basically selecting weights using a "known good" oracle (the input image). We know apriori the right answer for every texel, so we're fitting the weight to give the answer we want, not the other way around. The fact it's linear, sRGB, premul, etc is mostly(1) irrelevant - the compressor will simply try to find a weight that is the closest match to the oracle. This is the opposite of what you are doing in shaders with e.g. lighting calculation, where you don't know the answer, so need the maths to behave predictably.

**1:** mostly = Technically for linear RGB, when compressing color data you should have a gamma-corrected perceptual weighting on the errors - a diff of 0.1 on the dark side is more significant than a diff of 0.1 on the light side. We've never bothered implementing this because the "better answer" here is just to use sRGB in the first place.

**Comment by solidpixel** [comment]
Closing, as I think the conclusion was "no action needed".

**Comment by alecazam** [comment]
Interesting article here on why you don't want to interpolated srgb (or do for consistency with other incorrect apps).  Since it's locked into current hardware and it saves bits, then one just has to live with it for now. 

https://erikmcclure.com/blog/everyone-does-srgb-wrong-because/

"It doesn't help that we don't always necessarily want the correct interpolation. The reason direct interpolation in sRGB is wrong is because it changes the perceived luminosity. Notice that when going from red to green, the sRGB gradient gets darker in the middle of the transition, while the gamma-corrected one has constant perceived luminosity. However, an artist may prefer the sRGB curve to the linearized one because it puts more emphasis on red and green."
