### ISSUE TITLE
Color chanel is broken when using -normal_psnr

### ISSUE THREAD

**Issue by LuckyStarProg** [ARM-software/astc-encoder#27]
I am trying to compress my normal maps for my iOS game, but by default I receive some noise even in 4x4 block sizes. After further research I have found  -normal_psnr, but it makes texture in green Chanel (image attached).
I am using  Mali texture Compression Tool.
What I am doing wrong ?
Sorry for this question, I am pretty new in the field

Input .png image
![tex_photo_frame_01_woodoak_smooth_default_n](https://user-images.githubusercontent.com/19596973/44177747-e8eccf00-a0f7-11e8-9b02-ecee2ad38427.png)
Settings:
<img width="415" alt="2018-08-16 01 59 46" src="https://user-images.githubusercontent.com/19596973/44177808-31a48800-a0f8-11e8-8e93-1c1d823bcfd2.png">
<img width="600" alt="2018-08-16 02 00 19" src="https://user-images.githubusercontent.com/19596973/44177812-349f7880-a0f8-11e8-9756-b1e22258bfa5.png">
<img width="534" alt="2018-08-16 02 00 08" src="https://user-images.githubusercontent.com/19596973/44177816-3701d280-a0f8-11e8-8e5d-f521aa106a8d.png">
Output ASTC texture:
<img width="1280" alt="2018-08-16 02 05 50" src="https://user-images.githubusercontent.com/19596973/44177983-f2c30200-a0f8-11e8-810e-08a31c6f2a24.png">

**Comment by solidpixel** [comment]
Normal maps compressed with ASTC are packed into two component X+Y (like most normal compression). The texture red channel contains the X value and alpha channel contains the Y value. This channel split is used in order to allow uncorrelated compression for the two components (the uncorrelated channel is always the alpha channel for ASTC).

The Z value of the normal must be reconstructed in the shader core; assuming unit length normal vectors then Z = sqrt (1 - X^2 - Y^2).

HTH, 
Pete

**Comment by LuckyStarProg** [comment]
@solidpixel  So there is no possibility to receive normal map without modifications in the shader ? 

I am using Apple's SceneKit as a 3D Rendering API, so it doesn't have options to modify shaders, except I need to use Metal for archiving my goals ?

**Comment by solidpixel** [comment]
Nothing is stopping you compressing it as a normal RGB texture, but you'll get worse image quality.

**Comment by solidpixel** [comment]
Closing - original question was answered.
