### ISSUE TITLE
option to disable all prints

### ISSUE THREAD

**Issue by malytomas** [ARM-software/astc-encoder#304]
https://github.com/ARM-software/astc-encoder/blob/a287627df60809a2a32fe959757d7b3112716a6f/Source/astcenc_weight_align.cpp#L500

I am using standard input/output pipes for communicating between processes in my automatic asset pipeline processing.
Unfortunately, printing anything from the library makes the processing fail, which prevents me from debugging it.

Could you add an option to completely disable all prints, or a way to redirect them into a custom callback function?
Thanks.

**Comment by solidpixel** [comment]
Agree that this makes sense to add. Note that prints are already compiled out in release builds; you'll only hit them in debug builds.

**Comment by solidpixel** [comment]
Decided that these logs are pretty low value unless you are a codec developer, so rather than complicating the runtime API I've moved them all to be guarded by the DIAGNOSTICS build option at compile time (meaning that they can also be enabled in release builds, which I'll find useful). Builds without this set should now be logging free ...
