### ISSUE TITLE
About astc encoder configuration

### ISSUE THREAD

**Issue by mingugu25** [ARM-software/astc-encoder#34]
Is there a way to get the encoder configuration about best configuration and total configurations?
configuration include:partition count & partition index ,color mode & decimation

**Comment by solidpixel** [comment]
There isn't really any single "best" configuration in terms of command line settings. Like any lossy compression it's a tradeoff between three things:

- Image quality
- Bit rate
- Compression time

Exactly what is "best" really depends on what you are trying to achieve. Being better at bitrate will normally make the other two worse, for example. 

For most practical purposes exhaustive compression (testing every option in the search space) is too slow, so total configuration count is rarely a useful metric because the whole aim of a fast compressor is to drop areas of the search space which are unlikely to be useful to search.
