### ISSUE TITLE
Question on compressing atlases

### ISSUE THREAD

**Issue by septag** [ARM-software/astc-encoder#429]
Hi,
I'm trying to compress packed texture atlases. There are some areas between each texture/padding that we don't care. but when compressing, there are artifacts near the edges of images because of those spaces.
Is there a way that I can avoid that ? like providing a bit mask or something similar for the encoder ? 

Thanks

**Comment by solidpixel** [comment]
The usual fix for this is to preprocess the texture before compression to extrude the closest real edge color into the padding region, instead of e.g. using constant black. This gives the compressor a similar set of colors to compress which avoids most of the problems.  

This approach is also useful for alpha transparency, as a hard black edge and sharp alpha transition will still filter incorrectly because sample filtering is applied before the alpha transparency.

**Comment by solidpixel** [comment]
E.g. you can see the edge extrude on this image: 

https://user-images.githubusercontent.com/23016617/106572398-45464200-6530-11eb-9a15-c968c4ba485b.jpg
